#!/usr/bin/env ruby

require 'bundler/setup'

E = '.'
S = ' '

module Wall
  H = '─'
  V = '│'
  DR = '┌'
  DL = '┐'
  UR = '└'
  UL = '┘'
end
WALLS = Wall.constants.map &Wall.method(:const_get)

C = '@'
M = 'g'

module Tag
  NODE = 'Node'
  MONSTER = :monster
  PLAYER = :player
  WALL = :wall
end

require 'recs'

require 'require_all'
require_all './**/*.rb'

Game.new
