#!/usr/bin/env ruby

require 'bundler/setup'

H = '-'
V = '|'
E = '.'
S = ' '

WALLS = [H, V]

C = :player
M = :goblin

module Tag
  NODE = 'Node'
  MONSTER = :monster
  PLAYER = :player
  WALL = :wall
end

require 'recs'

require 'require_all'
require_all './**/*.rb'

Game.new
